### ISSUE TITLE
PYPI releases

### ISSUE THREAD

**Issue by mojeto** [hyperupcall/autoenv#161]
Hi,
I can see latest release 0.2.1 on github release page -> https://github.com/kennethreitz/autoenv/releases 
but 0.2.1 release isn't on pypi  -> https://pypi.python.org/simple/autoenv/

Also pypi has previous release version 1.0.0 which is greater than 0.2.x 
So when you run `pip install autoenv`  it installs version 1.0.0 which is old. 

Can we fix that please? 
Documentation start with `pip install autoenv` and it took me some time to figure out where the problem is.

cheers

**Comment by ssbarnea** [comment]
Indeed, there is something weird about this. I do see a 1.0.0 version on PYPI but is not listed as current release.

**Comment by kennethreitz** [comment]
this isn't a very well maintained project. i recommend using direnv instead. it's much better.

**Comment by rcotrina94** [comment]
Just install by using `git clone ...`. ;)

**Comment by inishchith** [comment]
@kennethreitz Thanks for the transfer. 
Just wanted to ask if you can add me as a collaborator on [`pypi`](https://pypi.org) for the project as I'll be maintaining this project from here one.

Thanks!

**Comment by szymonyang** [comment]
Same. Running `brew install autoenv` does not get the updated version, which lacks the feature of `AUTOENV_ENABLE_LEAVE`. Please clarify this.
