### ISSUE TITLE
shasum error

### ISSUE THREAD

**Issue by pc10201** [hyperupcall/autoenv#163]
```
cd project/

-bash: shasum: command not found

whoa
```

fix it on centos
`yum install perl-Digest-SHA -y`

**Comment by ssbarnea** [comment]
Sounds like an easy addition to a Makefile. Make a PRs!

**Comment by morbeo** [comment]
Perhaps fallback to `md5` or even `cksum` :neckbeard: if none of the sha are available.

**Comment by Gnouc** [comment]
@pc10201 What OS and shell do you use?

**Comment by hyperupcall** [comment]
Closing due to missing information and age of issue. `sha1sum` is in GNU coreutils and BusyBox, so maybe it's some issue related to old / ancient versions of CentOS or `which`. Feel free to open new issue if still relevant!
