### ISSUE TITLE
Seems to have issues when virtualenv dir has a dot (~/.venv/something)

### ISSUE THREAD

**Issue by Torniojaws** [hyperupcall/autoenv#177]
I installed autoenv using:
```
git clone git://github.com/kennethreitz/autoenv.git ~/.autoenv
echo 'source ~/.autoenv/activate.sh' >> ~/.bashrc
```
Then I sourced it:
``source ~/.bashrc``

Then I setup a dir with ``.env`` like this:
```
#!/bin/bash
source ~/.venv/project/bin/activate

export APP_SETTINGS="config.DevConfig"
export DATABASE_URL="mysql+pymysql://user:pass@localhost:3306/test?charset=utf8mb4"
```
But when I cd to that dir, I get a ``No such file or directory`` error:
```
autoenv:
autoenv: WARNING:
autoenv: This is the first time you are about to source /vagrant/project/.env:
autoenv:
autoenv:   --- (begin contents) ---------------------------------------
autoenv:     #!/bin/bash^M$
autoenv:     source /home/vagrant/.venv/project/bin/activate^M$
autoenv:     ^M$
autoenv:     export APP_SETTINGS="config.DevConfig"^M$
autoenv:     export DATABASE_URL="mysql+pymysql://user:pass@localhost:3306/test?charset=utf8mb4"^M$
autoenv:
autoenv:   --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) y
: No such file or directoryproject/bin/activate
: command not found
```
However, if I run the exact same command, it works just fine:
```
vagrant@vagrant-ubuntu-trusty-32:/vagrant/project$ source ~/.venv/project/bin/activate
(project) vagrant@vagrant-ubuntu-trusty-32:/vagrant/project$
```

What could be wrong?

**Comment by swolebro** [comment]
Just a hunch, it probably has to do with the `^M` of every line in your .env file. That's indicative that your file's lines are ending in a CR+LF, which is the Windows way of doing things, as opposed to just a LF, which is the Linux way.

Feed your .env file through a program like `dos2unix`, or configure your editor to automatically fix line endings, and you should be good to go.

For an explanation on what a mess line endings are, see: https://en.wikipedia.org/wiki/Newline

**Comment by hyperupcall** [comment]
Closing as the issue looks to be stale and not an issue with autoenv
