### ISSUE TITLE
brew version is old & doesn't have the leave function

### ISSUE THREAD

**Issue by sejgit** [hyperupcall/autoenv#180]
took me too long to figure out but once I compared the git versus the download from brew I discovered (!@#) that the leave functionality was not there.
Looks like an update to brew is needed.

**Comment by bryantbiggs** [comment]
@dasJ - Is it possible to tag and release the latest version so that a pull request against [HomeBrew](https://github.com/Homebrew/homebrew-core/blob/b33f5fc71b383329b130fb300a9ea290ef995f42/Formula/autoenv.rb#L4) can be made to include the latest changes? Currently `master` is 45 commits ahead of the `v0.2.1` release

**Comment by MemoryReload** [comment]
Aha, finally I found this! This made me mad, why leave scripts doesn't work. @dasJ  Would you please update the brew installation for us. Thank you!  : )

**Comment by markph0204** [comment]
@MemoryReload I've since moved over to **direnv** - which I really like.

**Comment by MemoryReload** [comment]
@markph0204   Thank you, I would have a try. 👍

**Comment by MemoryReload** [comment]
@markph0204 direnv is very awesome. But if it could show a virtual env prompt like autoenv does, it will be more friendly. I moved to direnv now. Thanks.

**Comment by markph0204** [comment]
@MemoryReload 

I added this to my ~/.bash_profile
https://github.com/direnv/direnv/wiki/Python#restoring-the-ps1

**Comment by MemoryReload** [comment]
@markph0204  I really should have read the Wiki !   Thanks a lot. I love it now.  👍

**Comment by northtree** [comment]
You could install the latest version via git.
https://github.com/kennethreitz/autoenv#using-git

**Comment by MemoryReload** [comment]
@northtree Yeah, I can manually install the latest version via git. But I just want to use brew to manage all my third-party packages as a default package manager. Thank you for your advice.
