### ISSUE TITLE
Can I deactivate used env if I cd to folder

### ISSUE THREAD

**Issue by ghost** [hyperupcall/autoenv#182]
Could current activated env be deactivated if I cd to folder which is not subfolder of current directory?

Also if I using such .env:
    source oenv/bin/activate
it works when I enter to this folder, but then when I go to subfolder I'm getting:
    bash: oenv/bin/activate: No such file or directory
I can fix it using absolute path, but it will be activated twice, isn't it.

@kennethreitz

**Comment by hyperupcall** [comment]
It looks like this is a dup of #30. Gonna close this in favor of that issue
