### ISSUE TITLE
removing autoenv

### ISSUE THREAD

**Issue by dbinetti** [hyperupcall/autoenv#185]
So say someone wants to remove autoenv -- I'm asking for a friend... :-P 

But then once doing `brew uninstall` they get this error:

`-bash: /usr/local/opt/autoenv/activate.sh: No such file or directory`

But my friend can't figure out where that command is being run.  What should my friend do?

**Comment by Gnouc** [comment]
Does he get the error when running on new terminal?

**Comment by dbinetti** [comment]
Yes, he does

**Comment by Gnouc** [comment]
Checking README.md:

```
echo "source $(brew --prefix autoenv)/activate.sh" >> ~/.bash_profile
```

So temporary works is removing that line from `~/.bash_profile`

**Comment by dbinetti** [comment]
My friend thanks you!

**Comment by hyperupcall** [comment]
Closing this issue as it appears solved :P
