### ISSUE TITLE
autoenv installed from pypi is outdated

### ISSUE THREAD

**Issue by arturtamborski** [hyperupcall/autoenv#187]
Hi,

I've installed autoenv by issuing `pip install autoenv` which worked fine but it installed an outdated version (release 1.0.0 last updated in 2012), which does not respect new environment variables, such as `AUTOENV_ENV_FILENAME`.

This can certainly catch someone off guard as It's not mentioned anywhere.

Please update pypi release with latest source or at least add note to readme file that pypi release is outdated.

Thanks.

**Comment by inishchith** [comment]
@arturtamborski Thanks for raising this. I'll make sure to add a note.
