### ISSUE TITLE
Freeze when running activate.sh on Mac Catalina OS

### ISSUE THREAD

**Issue by koreazombie** [hyperupcall/autoenv#188]
Hello.

Updated to Mac Catalina OS. I've tested it on more than one Mac and have the same thing.

**Comment by hche608** [comment]
I have the same issue

**Comment by Daoctor** [comment]
same issue when running `source $(brew --prefix autoenv)/activate.sh` on .zshrc.

**Comment by sennav** [comment]
I did a little debugging on this and it seems `activate.sh` enters a infinite loop trying to search all `.env` files recursively. The following line is supposed to break a "while true" loop:
https://github.com/inishchith/autoenv/blob/53fa011debe9dbacb71956a124e805aea2ff5d3b/activate.sh#L34
But in my machine it ends up comparing ` [ / '=' /System/Volumes/Data ']'` forever. So, I suspect that the output of:
https://github.com/inishchith/autoenv/blob/53fa011debe9dbacb71956a124e805aea2ff5d3b/activate.sh#L15
changed in the new version of OSX (specifically I suspect the output of `df -P` changed somehow), I don't have the old version now so I can't compare but I can check with other people tomorrow.

One quick fix is to hard code line 15 to `_mountpoint="/"` (works for me at least). It should work for the trivial cases but I don't fully understand the need of using `df`, I guess it's probably to support multiple mounting points (different hard disks?).

Anyway, I'm not an expert in shell scripting but I'm happy to help if you can guide me in the right direction.

**Comment by liufuyang** [comment]
Setting line 15 `_mountpoint="/" ` seems working for me as well.

**Comment by martnu** [comment]
The diff is in the `df -P "${PWD}"`.

On Catalina:
```
Filesystem   512-blocks      Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk1s1  976490576 532032976 420124688    56% 4463321 4877989559    0%   /System/Volumes/Data
```

On Mojave:
```
Filesystem   512-blocks      Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk1s1  976490576 532032976 420124688    56% 4463321 4877989559    0%   /
```

**Comment by meermanr** [comment]
On my system I've addressed this by adding a second break condition:

```diff --git a/activate.sh b/activate.sh
index 6553e98..18d3d33 100755
--- a/activate.sh
+++ b/activate.sh
@@ -32,6 +32,7 @@ ${_file}"
                                fi
                        fi
                        [ "$(\pwd -P)" = "${_mountpoint}" ] && \break
+                       [ "$(\pwd -P)" = "/" ] && \break
                        \command -v chdir >/dev/null 2>&1 && \chdir "$(\pwd -P)/.." || builtin cd "$(pwd -P)/.."
                done
        )```

**Comment by meermanr** [comment]
It seems Catalina is using a new "bi-directional wormhole in path traversal" [called firmlinks](https://devstreaming-cdn.apple.com/videos/wwdc/2019/710aunvynji5emrl/710/710_whats_new_in_apple_file_systems.pdf).

I've not found any tools which are firmlink-aware...

**Comment by eXamadeus** [comment]
From their slide presentation:

![image](https://user-images.githubusercontent.com/37161095/67686331-e9742d00-f96c-11e9-9959-9ba0999f2e41.png)

heh...

**Comment by s5b** [comment]
Further to the comments here, I was having a lot of trouble with `autoenv` under macOS _Catalina_, running `zsh` (Apple native), with _zprezto_. Now, _zprezto_ has an `alias` for `cd`, which I have disabled. 

And I have also implemented the change recommend by **meermanr**. 

But changing to a new directory prompts with the "`Are you sure you want to allow this?`" , as it should, but just hangs when answering "y". The reason? 

Well, it appears that `rm` (in my environment, again through _zprezto_) is aliased to "`rm -i`". And without a _backslash_ on the front of the `rm` in the `/usr/local/opt/autoenv/activate.sh` script will hang, of course. 

**Solution:** put a _backslash_ on the front of the `rm` command (just like the existing `cp` and `grep` commands in the same script.)

**Comment by J-Liu** [comment]
> On my system I've addressed this by adding a second break condition:
> 
> ```diff
> index 6553e98..18d3d33 100755
> --- a/activate.sh
> +++ b/activate.sh
> @@ -32,6 +32,7 @@ ${_file}"
>                                 fi
>                         fi
>                         [ "$(\pwd -P)" = "${_mountpoint}" ] && \break
> +                       [ "$(\pwd -P)" = "/" ] && \break
>                         \command -v chdir >/dev/null 2>&1 && \chdir "$(\pwd -P)/.." || builtin cd "$(pwd -P)/.."
>                 done
>         )```
> ```

It does work for `.env`, but `.env.leave` doesn't.
Is it the same issue?

**Comment by TeddyHartanto** [comment]
@J-Liu the quick fix proposed by @sennav works for both the `.env` and `.env.leave` in my case:
> One quick fix is to hard code line 15 to _mountpoint="/" (works for me at least). It should work for the trivial cases but I don't fully understand the need of using df, I guess it's probably to support multiple mounting points (different hard disks?).

I think the issue here is that as @martnu have showed us, the `_mountpoint` on Catalina is pointing to a different directory that the script didn't expect. It ran into an infinite loop because the termination condition isn't met. You can hard code it to `/` for now.

**Comment by J-Liu** [comment]
@TeddyHartanto 
I did replace `${_mountpoint}` into `/`, but `env.leave` doesn't work.

**Comment by TeddyHartanto** [comment]
@J-Liu have you done `export AUTOENV_ENABLE_LEAVE="true"`?

**Comment by J-Liu** [comment]
@TeddyHartanto 
<img width="318" alt="Screen Shot 2019-11-18 at 21 53 17" src="https://user-images.githubusercontent.com/1065112/69058032-d9bca580-0a4d-11ea-8399-13674293e458.png">
Yes I did, so, it is really weird.

**Comment by Dahie** [comment]
For future reference, the autoenv version available in homebrew is outdated and does not contain the fixes in https://github.com/inishchith/autoenv/pull/190. I manually changed the `activate.sh` and it works now.

**Comment by kingofsevens** [comment]
I mentioned this #189 but let me mentioned this here again. Does anybody experiencing a longer wait in changing directories or with autocomplete when changing directories. While autoenv disabled changing directories is instantaneous, but with autoenv it takes up to 3-4 seconds and with autocomplete as well. It sometimes unbearable. Also affected some of my bash scripts.

**Comment by yozlet** [comment]
@inishchith Given @Dahie's comment above, maybe it's time for a 0.2.2 release (or something)?

**Comment by SEONGTAEK01** [comment]
I've solved the problem replace`${_mountpoint}` with `/`. But still had a problem that if I change a directory using 'cd target-dir' then autoenv works. If I change a directory using alias registered in shell resource file like `.zshrc`, autoenv had not worked. The alias was like, "alias="Users/taek/dev/src" without 'cd' command. So I added 'cd' command then it all works :)
Not directly related to the title but post a reply for someone who suffer from similar problem.

**Comment by phrfpeixoto** [comment]
I just installed from brew and this issue is still present.

**Comment by animate-object** [comment]
> I just installed from brew and this issue is still present.

Same. Bump for this: 

> @inishchith Given @Dahie's comment above, maybe it's time for a 0.2.2 release (or something)?

**Comment by otobrglez** [comment]
Hey guys!

Just wanted to let u know that to this date; this is still a problem.

Versions: macOS Catalina - 10.15.6 (19G73), autoenv: stable 0.2.1, HEAD (via homebrew)

Hope it helps someone out there,... Cheers!

**Comment by chkdmin** [comment]
Hello

This problem has already been fixed and Merge on Master Branch.
But I don't know why not update new release
Check out this link to install using git
https://github.com/inishchith/autoenv#using-git
