### ISSUE TITLE
sourcing of activate.sh on OSx Big Sur causes hanging in Terminal

### ISSUE THREAD

**Issue by numberwhun** [hyperupcall/autoenv#196]
I am using autoenv as part of my project that also employs virtualenvwrapper.  I upgraded to Big Sur recently and am installing my software.  Unfortunately, after installing autoenv using brew, adding the 'source' line to my .bash_profile and then sourcing that file, the command prompt hangs as if it is processing something.  

Commenting out the source of activate.sh stops the issue.  I gave it some time, but the hanging continues indefinitely.  When I open a new terminal window, the same hanging occurs.

My system specs are:

Mac OSx 11.0.1 (20B29) (Big Sur)
Autoenv version: stable 0.2.1, HEAD
Python:  3.8.2

**Comment by numberwhun** [comment]
I attempted to trace the system calls using dtruss, but received the following:

```
$ sudo dtruss /usr/local/opt/autoenv/activate.sh 
Password:
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute /usr/local/opt/autoenv/activate.sh: (os/kern) failure
```

**Comment by numberwhun** [comment]
I took and uninstalled autoenv (install and uninstall both via pip), and re-installed it using brew.   Even after installing with brew, the issue persisted.

**Comment by 2young-2simple-sometimes-naive** [comment]
This is the same reason as [#193 ](https://github.com/inishchith/autoenv/issues/193). The brew version is outdated. Install using git clone will fix this.
