### ISSUE TITLE
Allow .env file to be ignored permanently

### ISSUE THREAD

**Issue by chrishas35** [hyperupcall/autoenv#21]
I have a use case where I'd like to no longer be prompted to source a particular .env.  The particular use case is a Django project template folder where the .env is not valid as it's a Django template w/ `{{ project_name }}` that is not yet rendered, but there might be other reasons someone wants to ignore a .env file.

Thoughts around implementation would be to add an ignore option to the "Are you sure you want to allow this?" prompt. If the individual chooses to ignore the file, write it to ~/.autoenv_ignored. I don't see a reason to include the hash in .autoenv_ignored, but can if desired. To unignore a .env file you'd have to manually edit .autoenv_ignored, or we'd have to create a function to unignore.

Thoughts on adding this and the implementation plan?  I can hack on the code a bit if this sounds like an acceptable plan.

**Comment by hyperupcall** [comment]
This has been implemented by #226. I'll be making a `v0.4.0` release that includes it in the coming days. Cheers!
