### ISSUE TITLE
Error bash: 1: No such file or directory

### ISSUE THREAD

**Issue by mg-dev25** [hyperupcall/autoenv#218]
Hello, the command work well, but every time I move to another directory the `bash: 1: No such file or directory` message appeared. I'm on arch Linux and used bash 5.1.16. I try to search if there were a solution but found nothing.

The activate.sh is source correctly, but when I run it manually it give me the same error. Maybe an issue with the files?

Any idea, for removing this error?
Thanks

**Comment by hyperupcall** [comment]
Hmm, I could not reproduce on my machine - what is your installation method - npm or Git, and which version is installed? Thanks

**Comment by mg-dev25** [comment]
It is installed with a package manager YAY. But it's build with the last git version.

**Comment by hyperupcall** [comment]
@mg-dev25 Does using the following `PKGBUILD` fix it for you? The current one in the AUR is out of date by _4 years_ and doesn't properly install it in the correct place. Note that this installs version `v0.3.0`, and some features on head like `AUTOENV_PRESERVE_CD` may not be implemented.

```sh
# Maintainer: hyperupcall <edwin@kofler.dev>

pkgname=autoenv
pkgver=0.3.0
pkgrel=1
pkgdesc='Directory-based enviroments'
arch=('any')
url='https://github.com/hyperupcall/autoenv'
license=('MIT')
source=("$pkgname"::'git+https://github.com/hyperupcall/autoenv.git#commit=025e52fbf033cc094943febec71e2ad81a5de84f')
sha256sums=('SKIP')
depends=('bash')
optdepends=('zsh: if preferred over bash')
makedepends=('git')
conflicts=('autoenv-git')

package() {
  cd "$pkgname"

  install -D -m755 './activate.sh' "${pkgdir}/etc/profile.d/autoenv_activate.sh"
  install -D -m644 './LICENSE' "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
```

You can install it like so:

```sh
# In a directory with only the 'PKGBUILD' file:
sudo pacman -S pacman
makepkg -i
```
