### ISSUE TITLE
autoenv_check_authz_and_run:7: read-only variable: status

### ISSUE THREAD

**Issue by kis87988** [hyperupcall/autoenv#227]
**Platform**
 - Operating system and version Ubuntu 20.04
 - Shell and version zsh 5.8
 - autoenv installation method autoinstall, (git)
 - autoenv version master head
 
**Describe the bug**
Config with .env and .env.leave
run under zsh.
enter the directory 
```
$ cd test
autoenv_check_authz_and_run:7: read-only variable: status
$ pwd
/home/user/test
```
however, when I use bash to run it.
it shows these infomation
```
[autoenv] New or modified env file detected:
--- .env contents -----------------------------------------------------------------------------------------------------------------------------------------------------------

AUTOENV_ENABLE_LEAVE=1
conda activate test
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[autoenv] Authorize this file? (y/N/D) 
```

after I authorized, it can run under zsh.

**Expected behavior**
it should prompt the `authorize this file` part

**Additional context**

N/A

**Comment by hyperupcall** [comment]
Thank you for your report! Fixed on `HEAD` by a6c347fe406fc1e39bec7fca9f609891a58a3de7
